name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  integration-continue:
    name: "CI — Build & Push Docker"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installation des dépendances
        run: npm install

      - name: Lancement des tests
        run: npm test

      - name: Login sur Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build de l'image Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mon-app:latest .

      - name: Push sur Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mon-app:latest

  deploiement-continu:
    name: "CD — Deploy sur Minikube"
    runs-on: ubuntu-latest
    needs: integration-continue

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Déploiement sur Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
